### ISSUE TITLE
Support for half stars

### ISSUE THREAD

**Issue by hkhuu1011** [LunarLogic/starability#26]
Will half star ratings be supported in the near future?

**Comment by szynszyliszys** [comment]
Hi @hkhuu1011 ,
I don't think I am going to ship it as a part of library. You can see my answer to a sub-rating question some time ago: https://github.com/LunarLogic/starability/issues/9

**Comment by mislav** [comment]
Support for *displaying* half-star ratings via `.starability-result` might be useful for displaying average ratings. It's not necessary to make support for *submitting* half-star ratings, since that would be at the same time more complex to implement as well as harder to use.

<img width="177" alt="screen shot 2018-02-20 at 4 25 12 pm" src="https://user-images.githubusercontent.com/887/36432555-c24bfe98-165a-11e8-929d-9da67a329293.png">

Here are the changes needed to make it happen:

```scss
@import "starability/starability-scss/starability/growRotate";

.starability-result {
  $star-count-result: $star-count - 1;
  @while $star-count-result > 0 {
    &[data-rating="#{$star-count-result}.5"]::after {
      width: $star-count-result * $star-size + $star-size / 2;
    }
    $star-count-result: $star-count-result - 1;
  }
}
```
